# Generated by Django 5.2.2 on 2025-06-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_delete_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='total_producto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
