# Generated by Django 5.2.2 on 2025-06-06 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_delete_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('cantidad_entregada', models.PositiveIntegerField()),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='pedidos.detallepedido')),
            ],
        ),
    ]
