# Generated by Django 3.2 on 2025-06-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro'), ('kraft', 'Kraft'), ('transparente', 'Transparente')], default='blanco', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(choices=[('pequeña', 'Pequeña'), ('mediana', 'Mediana'), ('grande', 'Grande')], default='grande', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_material',
            field=models.CharField(choices=[('papel', 'Papel'), ('plastico', 'Plástico'), ('biodegradable', 'Biodegradable'), ('tnt', 'TNT')], default='kraft', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
