# Generated by Django 5.2.2 on 2025-06-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20250604_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='coste_producción_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
