# Generated by Django 5.1.2 on 2025-06-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(max_length=20, unique=True)),
                ('nombre_fantasia', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion_despacho', models.CharField(max_length=200)),
            ],
        ),
    ]
