# Generated by Django 5.1.2 on 2025-06-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cod_cliente',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
