# Generated by Django 5.1.2 on 2025-06-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_id_alter_cliente_cod_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
